version: '3.8'

services:
  backend:
    build:
      context: ./collatask-backend
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.collatask.com`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
    ports:
        - "3000:3000"
    networks:
      - app_network

  frontend:
    build:
      context: ./collatask-frontend
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`collatask.com`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    ports:
        - "80:80"
    networks:
      - app_network

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.myresolver.acme.email=jules@collatask.com"
      - "--certificatesresolvers.myresolver.acme.storage=/etc/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/etc/letsencrypt"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
