services:
  backend:
    build:
      context: ./collatask-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - APP_URL=${APP_URL}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_JWT_SECRET=${EMAIL_JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - db

  frontend:
    build:
      context: ./collatask-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_APP_URL=${VITE_APP_URL}

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./structure.sql:/docker-entrypoint-initdb.d/structure.sql

volumes:
  pgdata:
